"""Three different things were being added together and called "spend".

`provider_calls.cost_usd` holds a number. Until this module it did not say
what kind of number, and `arie.usage` summed them all into one total that
`arie.limits` then compared against a real-money monthly allowance. The
audited organization had "spent" $50.33 against a $50.00/month ceiling
entirely in the simulated catalogue's fictional prices, generated by test
fixtures. A real cascade (Abstract + Hunter + Apollo) costs about $0.026; the
simulated one "costs" $1.0078.

The three kinds, kept apart from here on:

**Modelled spend** — `SIMULATED_CATALOGUE`. A benchmark assumption, not a
price. `arie/providers/catalog.py` says so itself: "Every parameter here is an
assumption." It must never consume a monetary allowance, and it must never be
hidden either: a simulated run is real work with a real modelled cost, and the
product reports it under its own name.

**Estimated live provider cost** — `MODELLED_CREDIT_EQUIVALENT` and
`MODELLED_LIST_PRICE`. A *real* provider call, priced from a vendor credit or
a published rate because the vendor did not state a figure. This is an
estimate of what the call is worth, not a record of money leaving an account,
and calling it "actual spend" would be a lie with a decimal point on it.

**Actual spend** — `VENDOR_BILLED`, and more precisely the separate
`actual_cost_usd` column. Money the vendor reported. Independent of everything
above: a real call made against free credits correctly records
`actual_cost_usd = 0` while still being a real provider call.

`real_provider_call` is therefore derived, not stored — it is "the basis is
not `SIMULATED_CATALOGUE`", which is exactly the question, and a fourth column
carrying the same fact could only ever disagree with the other three.
"""

from __future__ import annotations

from enum import StrEnum

__all__ = [
    "ACTUAL_SPEND_SQL",
    "ESTIMATED_LIVE_SQL",
    "MODELLED_SPEND_SQL",
    "CostBasis",
    "is_real_provider_call",
]


class CostBasis(StrEnum):
    """Must stay in sync with `provider_calls_cost_basis_check` (0043)."""

    SIMULATED_CATALOGUE = "simulated_catalogue"
    """A fictional benchmark price. Never money, never billable."""

    MODELLED_CREDIT_EQUIVALENT = "modelled_credit_equivalent"
    """A real call, priced from the vendor credit it consumed."""

    MODELLED_LIST_PRICE = "modelled_list_price"
    """A real call, priced from the vendor's published rates."""

    VENDOR_BILLED = "vendor_billed"
    """A figure the vendor itself reported for this call."""


_REAL = frozenset(
    {
        CostBasis.MODELLED_CREDIT_EQUIVALENT,
        CostBasis.MODELLED_LIST_PRICE,
        CostBasis.VENDOR_BILLED,
    }
)


def is_real_provider_call(cost_basis: str | None) -> bool:
    """Did this row represent a call to a real vendor?

    `None` — a zero-cost cache hit, which records no basis because no call
    happened — is not one. Neither is an unrecognised value: a basis this
    module does not know about is not evidence that real money was involved,
    and treating it as real is the direction that overstates spend.
    """
    if cost_basis is None:
        return False
    try:
        return CostBasis(cost_basis) in _REAL
    except ValueError:
        return False


MODELLED_SPEND_SQL = "cost_basis IS NOT DISTINCT FROM 'simulated_catalogue'"
"""Simulated catalogue cost.

`IS NOT DISTINCT FROM` rather than `=` so a NULL basis lands here. Migration
0043 backfilled every historical NULL to `simulated_catalogue`, but a cache
hit still writes NULL by design, and a zero-cost row belongs on the side that
cannot consume an allowance.
"""

ESTIMATED_LIVE_SQL = (
    "cost_basis IN ('modelled_credit_equivalent', 'modelled_list_price', 'vendor_billed')"
)
"""Every real provider call, priced however it was priced. This is the
denominator for "how much real provider work happened", not for money."""

ACTUAL_SPEND_SQL = "actual_cost_usd IS NOT NULL"
"""Money a vendor actually reported. Deliberately keyed on the column rather
than on `cost_basis`: a `vendor_billed` row whose figure never arrived has
nothing to add, and a free-credit call reports 0 here and means it."""
