-- =============================================================================
-- 0043_cost_basis_vocabulary.sql — what a recorded cost actually *is*.
--
-- `provider_calls.cost_usd` held three different kinds of number in one
-- column, and `arie.usage` summed them together:
--
--   * the simulated catalogue's fictional prices (a full cascade is $1.0078,
--     and `arie/providers/catalog.py` says plainly "Every parameter here is an
--     assumption"),
--   * a modelled USD equivalent of a vendor credit actually consumed, and
--   * (reserved, never yet written) a figure a vendor actually billed.
--
-- That sum reached `arie.limits.get_usage_against_limits` as
-- `modeled_spend_used_usd` and was compared against a real-money monthly
-- allowance. The audited organization had consumed $50.33 against a $50.00/mo
-- ceiling entirely in fictional prices, generated by test fixtures. A live
-- cascade costs about $0.026; the simulated one "costs" $1.0078, 38x more.
--
-- `cost_basis` already existed for exactly this purpose (0010) and was already
-- documented as naming what `cost_usd` is. It was simply never written on the
-- simulated path: 2939 of 2941 rows are NULL, and the only 2 non-NULL rows are
-- the real Hunter canary calls of 2026-09-01.
--
-- This migration does two things: backfills those 2939 rows to the value the
-- audit proved they are, and constrains the vocabulary so the next writer
-- cannot invent a fourth meaning. It deliberately does NOT add a column —
-- `actual_cost_usd` (0028) is already there for money actually billed, and it
-- is separate from the list-price equivalent by design.
-- =============================================================================

-- The backfill is scoped by `cost_basis IS NULL`, so it cannot touch the two
-- rows already classified as real calls. Establishing that every remaining
-- NULL row is a simulated-catalogue call is the audit's finding, not an
-- assumption this migration makes: `PROVIDER_MODE=simulated` for every
-- organization, and the only code that has ever written a non-NULL basis is
-- the live Hunter/Apollo adapter pair.
UPDATE provider_calls
   SET cost_basis = 'simulated_catalogue'
 WHERE cost_basis IS NULL;

ALTER TABLE provider_calls
    DROP CONSTRAINT IF EXISTS provider_calls_cost_basis_check;

ALTER TABLE provider_calls
    ADD CONSTRAINT provider_calls_cost_basis_check CHECK (
        cost_basis IS NULL OR cost_basis IN (
            'simulated_catalogue',        -- a fictional benchmark price; never money
            'modelled_credit_equivalent', -- a real call, priced from a vendor credit
            'modelled_list_price',        -- a real call, priced from published rates
            'vendor_billed'               -- a figure the vendor itself reported
        )
    );

-- NULL stays permitted rather than being forbidden outright: a cache hit is
-- recorded at zero cost with no basis (`arie.ledger.store` passes None when
-- `cache_hit=True`), and a basis on a row that cost nothing would be a claim
-- about a call that never happened.

COMMENT ON COLUMN provider_calls.cost_basis IS
    'What cost_usd is. ''simulated_catalogue'' is a fictional benchmark price '
    'and must never consume a monetary allowance. The other three describe a '
    'real provider call: ''vendor_billed'' is money the vendor reported, the '
    'two ''modelled_*'' values are list-price equivalents for a real call and '
    'are NOT actual spend. NULL only on a zero-cost cache hit.';

COMMENT ON COLUMN provider_calls.actual_cost_usd IS
    'Money actually billed, only when the vendor states it. Independent of '
    'cost_basis: a real call made against free credits correctly records 0 '
    'here while still being a real provider call.';
